[project]
name = "city_planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alexia Gutierrez Niño", email = "alexia300622@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
step0-planning = "step0_planning:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
